project_id = "wtrmrhfjrxdfkqpxteuq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.book-slot]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-appointment-reminders]
    verify_jwt = false
